import { useState } from 'react'
import { ArrowLeft, ArrowRight, ChatCircle, Exam, Folder, Plus } from '@phosphor-icons/react'

const surface = 'rounded-xl bg-white p-4 shadow-[0_10px_32px_rgba(76,29,149,0.11)] dark:bg-slate-900 dark:shadow-[0_14px_38px_rgba(0,0,0,0.32)]'
const action = 'flex h-10 items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-purple-700 to-purple-500 px-3 text-sm font-medium text-white shadow-[0_10px_26px_rgba(126,34,206,0.24)] transition-[transform,box-shadow] duration-300 ease-out hover:shadow-[0_14px_30px_rgba(126,34,206,0.3)] focus:outline-none focus:ring-2 focus:ring-purple-500/10 active:scale-[0.97] motion-reduce:transform-none'
const back = 'flex h-9 items-center gap-2 rounded-lg bg-slate-100 px-3 text-sm font-medium text-slate-700 transition-colors duration-300 ease-out hover:bg-purple-100 hover:text-purple-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-purple-500/15'

export default function HomePortal({ workspaces, conversations, onOpenChat, onNewChat, onOpenQuiz }) {
  const [view, setView] = useState('root')
  const [workspaceId, setWorkspaceId] = useState(null)
  const workspace = workspaces.find((item) => item.id === workspaceId)
  const chats = conversations.filter((item) => item.workspaceId === workspaceId).sort((a, b) => b.createdAt - a.createdAt)

  if (view === 'workspace' && workspace) return <Page><button onClick={() => setView('chat')} className={back}><ArrowLeft size={16} />Workspaces</button><div className="mt-4 flex items-end justify-between gap-3"><div><span className="text-xs font-medium uppercase tracking-[0.14em] text-purple-600 dark:text-purple-300">Workspace</span><h1 className="mt-1 text-xl font-semibold">{workspace.name}</h1><p className="mt-0.5 text-sm text-slate-500">Choose a conversation or start a new one.</p></div><button onClick={() => onNewChat(workspace.id)} className={action}><Plus size={17} />New chat</button></div><section className={`${surface} mt-4`}><div className="divide-y divide-slate-100 dark:divide-slate-800">{chats.map((chat) => <button key={chat.id} onClick={() => onOpenChat(chat)} className="group flex min-h-11 w-full items-center gap-3 rounded-lg px-2 py-2 text-left transition-colors duration-300 ease-out hover:bg-purple-50 dark:hover:bg-purple-500/10"><ChatCircle size={17} className="text-purple-600" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{chat.title}</span><span className="text-xs text-slate-500">{chat.messages.length} messages</span></span><ArrowRight size={16} /></button>)}{!chats.length && <p className="py-4 text-center text-sm text-slate-500">No conversations in this workspace yet.</p>}</div></section></Page>

  if (view === 'chat') return <Page><button onClick={() => setView('root')} className={back}><ArrowLeft size={16} />Home</button><div className="mt-4"><span className="text-xs font-medium uppercase tracking-[0.14em] text-purple-600 dark:text-purple-300">Chat</span><h1 className="mt-1 text-xl font-semibold">Choose a workspace</h1><p className="mt-0.5 text-sm text-slate-500">Open a workspace to view conversations or create a new chat.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{workspaces.map((item) => { const count = conversations.filter((chat) => chat.workspaceId === item.id).length; return <button key={item.id} onClick={() => { setWorkspaceId(item.id); setView('workspace') }} className={`${surface} group text-left transition-transform duration-300 ease-out hover:-translate-y-0.5 motion-reduce:transform-none`}><Folder size={22} className="text-purple-600 dark:text-purple-300" /><h2 className="mt-2 text-base font-semibold">{item.name}</h2><p className="mt-0.5 text-xs text-slate-500">{count} conversation{count === 1 ? '' : 's'}</p><span className="mt-3 flex items-center gap-1 text-sm font-medium text-purple-700 dark:text-purple-300">Open workspace<ArrowRight size={15} /></span></button> })}</div></Page>

  return <Page centered><div className="text-center"><span className="inline-flex rounded-full bg-purple-100 px-2.5 py-0.5 text-xs font-medium text-purple-700 dark:bg-purple-500/15 dark:text-purple-300">Choose your space</span><h1 className="mt-2 text-2xl font-semibold">What would you like to do?</h1><p className="mt-1 text-sm text-slate-500">Continue a conversation or test your knowledge.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={() => setView('chat')} className={`${surface} group text-left transition-transform duration-300 ease-out hover:-translate-y-0.5 motion-reduce:transform-none`}><ChatCircle size={24} className="text-purple-600" /><h2 className="mt-2 text-base font-semibold">Chat</h2><p className="mt-0.5 text-sm text-slate-500">Browse workspaces and conversations.</p><span className="mt-3 flex items-center gap-1 text-sm font-medium text-purple-700">View workspaces<ArrowRight size={16} /></span></button><button onClick={onOpenQuiz} className={`${surface} group text-left transition-transform duration-300 ease-out hover:-translate-y-0.5 motion-reduce:transform-none`}><Exam size={24} className="text-purple-600" /><h2 className="mt-2 text-base font-semibold">Quiz</h2><p className="mt-0.5 text-sm text-slate-500">Browse categories, quizzes, and results.</p><span className="mt-3 flex items-center gap-1 text-sm font-medium text-purple-700">View quiz categories<ArrowRight size={16} /></span></button></div></Page>
}

function Page({ children, centered = false }) { return <div className="relative min-h-0 flex-1 overflow-y-auto px-3 py-3 sm:px-4 sm:py-4 lg:px-6 lg:py-5"><div className={`mx-auto w-full max-w-5xl ${centered ? 'flex min-h-full flex-col justify-center' : ''}`}>{children}</div></div> }
