import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CheckCircle, Exam, Folder, Plus, SpinnerGap, Trash, XCircle } from '@phosphor-icons/react'
import { quizPaths } from '../lib/routes'
import CategoryDialog from './CategoryDialog'

const inputClass = 'w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition-[border-color,background-color] duration-300 ease-out placeholder:text-slate-400 focus:border-purple-400 focus:ring-2 focus:ring-purple-500/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100'
const primary = 'flex h-10 items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-purple-700 to-purple-500 px-3 text-sm font-medium text-white shadow-[0_10px_26px_rgba(126,34,206,0.24)] transition-[transform,box-shadow,opacity] duration-300 ease-out hover:shadow-[0_14px_30px_rgba(126,34,206,0.3)] focus:outline-none focus:ring-2 focus:ring-purple-500/10 active:scale-[0.97] disabled:cursor-not-allowed disabled:opacity-40 motion-reduce:transform-none'
const secondary = 'flex h-10 items-center justify-center gap-2 rounded-lg bg-slate-100 px-3 text-sm font-medium text-slate-700 transition-colors duration-300 ease-out hover:bg-purple-100 hover:text-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500/10 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-purple-500/15 dark:hover:text-purple-200'
const surface = 'rounded-xl bg-white p-4 shadow-[0_10px_32px_rgba(76,29,149,0.11)] dark:bg-slate-900 dark:shadow-[0_14px_38px_rgba(0,0,0,0.32)]'

function AnswerField({ question, value, onChange, disabled }) {
  const options = question.options || []
  const label = `Answer for: ${question.prompt}`
  if (question.responseMode === 'single_choice' || question.responseMode === 'boolean') {
    const choices = options.length ? options : ['True', 'False']
    return <div role="radiogroup" aria-label={label} onKeyDown={(event) => { if (!['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) return; event.preventDefault(); const current = Math.max(0, choices.indexOf(value)); const direction = ['ArrowRight', 'ArrowDown'].includes(event.key) ? 1 : -1; const next = (current + direction + choices.length) % choices.length; onChange(choices[next]); event.currentTarget.querySelectorAll('[role="radio"]')[next]?.focus() }} className="grid gap-2 sm:grid-cols-2">{choices.map((option, index) => { const selected = value === option; return <button key={option} type="button" role="radio" aria-checked={selected} tabIndex={selected || (!value && index === 0) ? 0 : -1} disabled={disabled} onClick={() => onChange(option)} className={`flex min-h-10 items-center gap-2 rounded-lg border px-3 py-2 text-left text-sm transition-[border-color,background-color,color] duration-300 ease-out focus:outline-none focus:ring-2 focus:ring-purple-500/10 ${selected ? 'border-purple-400 bg-purple-100 font-medium text-purple-900 dark:border-purple-500 dark:bg-purple-500/20 dark:text-purple-100' : 'border-slate-200 bg-white hover:border-purple-300 hover:bg-purple-50 dark:border-slate-700 dark:bg-slate-950 dark:hover:bg-purple-500/10'}`}><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${selected ? 'border-purple-600 bg-purple-600 text-white' : 'border-slate-300'}`}>{selected && <Check size={12} weight="bold" />}</span>{option}</button> })}</div>
  }
  if (question.responseMode === 'multiple_choice') { const selected = Array.isArray(value) ? value : []; return <div className="grid gap-2 sm:grid-cols-2">{options.map((option) => { const checked = selected.includes(option); return <label key={option} className={`flex min-h-10 cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm transition-colors duration-300 ${checked ? 'border-purple-400 bg-purple-100 font-medium text-purple-900 dark:bg-purple-500/20 dark:text-purple-100' : 'border-slate-200 bg-white hover:bg-purple-50 dark:border-slate-700 dark:bg-slate-950'}`}><input type="checkbox" className="sr-only" disabled={disabled} checked={checked} onChange={() => onChange(checked ? selected.filter((item) => item !== option) : [...selected, option])} /><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${checked ? 'bg-purple-600 text-white' : ''}`}>{checked && <Check size={12} />}</span>{option}</label> })}</div> }
  if (question.responseMode === 'long_text') return <textarea aria-label={label} value={value || ''} disabled={disabled} onChange={(event) => onChange(event.target.value)} rows="5" placeholder="Write your answer here…" className={`${inputClass} resize-y py-2`} />
  return <input aria-label={label} type={question.responseMode === 'number' ? 'number' : 'text'} value={value || ''} disabled={disabled} onChange={(event) => onChange(event.target.value)} placeholder="Type your answer…" className={`${inputClass} h-10`} />
}

const answered = (question, answer) => question.responseMode === 'multiple_choice' ? Array.isArray(answer) && answer.length > 0 : String(answer ?? '').trim().length > 0

export default function QuizPage({ route, onNavigate, providerReady, categories, quizzes, attempts, onAddCategory, onDeleteCategory, onSaveQuiz, onSaveAttempt, onOpenSettings, onGenerate, onGrade }) {
  const [view, setView] = useState('categories')
  const [categoryId, setCategoryId] = useState(route.categoryId || categories[0]?.id || '')
  const [description, setDescription] = useState('')
  const [instructions, setInstructions] = useState('')
  const [categoryDialogOpen, setCategoryDialogOpen] = useState(false)
  const [quiz, setQuiz] = useState(null)
  const [answers, setAnswers] = useState({})
  const [result, setResult] = useState(null)
  const [attempt, setAttempt] = useState(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const count = useMemo(() => quiz?.questions.filter((q) => answered(q, answers[q.id])).length || 0, [quiz, answers])
  const category = categories.find((item) => item.id === categoryId)
  const categoryQuizzes = quizzes.filter((item) => item.categoryId === categoryId)
  const navigate = useCallback((quizView, path, details = {}, replace = false) => onNavigate({ page: 'quiz', quizView, ...details }, path, replace), [onNavigate])

  useEffect(() => {
    const nextView = route.quizView || 'categories'
    if (nextView === 'categories') { setView(nextView); return }
    if (nextView === 'category' || nextView === 'create') {
      if (!categories.some((item) => item.id === route.categoryId)) { navigate('categories', quizPaths.categories, {}, true); return }
      setCategoryId(route.categoryId)
      setView(nextView)
      return
    }
    if (nextView === 'detail' || nextView === 'taking') {
      const savedQuiz = quizzes.find((item) => item.id === route.quizId)
      if (!savedQuiz) { navigate('categories', quizPaths.categories, {}, true); return }
      if (quiz?.id !== savedQuiz.id) { setQuiz(savedQuiz); setAnswers({}); setResult(null); setAttempt(null); setError('') }
      setCategoryId(savedQuiz.categoryId)
      setView(nextView)
      return
    }
    if (nextView === 'result') {
      const savedAttempt = attempts.find((item) => item.id === route.attemptId)
      const savedQuiz = savedAttempt && quizzes.find((item) => item.id === savedAttempt.quizId)
      if (!savedAttempt || !savedQuiz) { navigate('categories', quizPaths.categories, {}, true); return }
      setQuiz(savedQuiz)
      setCategoryId(savedQuiz.categoryId)
      setAnswers(savedAttempt.answers)
      setResult(savedAttempt.result)
      setAttempt(savedAttempt)
      setView(nextView)
    }
  }, [route.quizView, route.categoryId, route.quizId, route.attemptId, categories, quizzes, attempts, quiz?.id, navigate])

  const openQuiz = (item) => { setQuiz(item); setAnswers({}); setResult(null); setAttempt(null); setError(''); navigate('detail', quizPaths.detail(item.id), { quizId: item.id }) }
  const takeQuiz = () => { setAnswers({}); setResult(null); setAttempt(null); setError(''); navigate('taking', quizPaths.taking(quiz.id), { quizId: quiz.id }) }
  const createQuiz = async (event) => { event.preventDefault(); if (!providerReady) { onOpenSettings(); return } setBusy(true); setError(''); try { const generated = await onGenerate({ description: description.trim(), instructions: instructions.trim() }); const saved = { ...generated, id: crypto.randomUUID(), categoryId, createdAt: Date.now() }; onSaveQuiz(saved); openQuiz(saved) } catch (cause) { setError(cause.message) } finally { setBusy(false) } }
  const submit = async () => { if (count !== quiz.questions.length) { setError('Answer every question before submitting.'); return } setBusy(true); setError(''); try { const graded = await onGrade(quiz, answers); const saved = { id: crypto.randomUUID(), quizId: quiz.id, categoryId: quiz.categoryId, answers, result: graded, completedAt: Date.now() }; setResult(graded); setAttempt(saved); onSaveAttempt(saved); navigate('result', quizPaths.result(saved.id), { attemptId: saved.id }) } catch (cause) { setError(cause.message) } finally { setBusy(false) } }
  const showAttempt = (item) => { const savedQuiz = quizzes.find((entry) => entry.id === item.quizId); if (!savedQuiz) return; setQuiz(savedQuiz); setAnswers(item.answers); setResult(item.result); setAttempt(item); navigate('result', quizPaths.result(item.id), { attemptId: item.id }) }
  const startAnother = () => { setQuiz(null); setAnswers({}); setResult(null); setAttempt(null); setDescription(''); setInstructions(''); navigate('create', quizPaths.create(categoryId), { categoryId }) }

  if (view === 'categories') return <Page><div className="flex items-end justify-between gap-3"><div><span className="text-xs font-medium uppercase tracking-[0.14em] text-purple-600">Quiz</span><h1 className="mt-1 text-xl font-semibold">Choose a category</h1><p className="mt-0.5 text-sm text-slate-500">Open a category to view its saved quizzes.</p></div><button type="button" onClick={() => setCategoryDialogOpen(true)} className={primary}><Plus size={17} />Add category</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((item) => <button key={item.id} onClick={() => { setCategoryId(item.id); navigate('category', quizPaths.category(item.id), { categoryId: item.id }) }} className={`${surface} text-left transition-transform duration-300 hover:-translate-y-0.5 motion-reduce:transform-none`}><Folder size={22} className="text-purple-600" /><h2 className="mt-2 text-base font-semibold">{item.name}</h2><p className="mt-0.5 text-xs text-slate-500">{quizzes.filter((q) => q.categoryId === item.id).length} quizzes · {attempts.filter((a) => a.categoryId === item.id).length} attempts</p></button>)}</div><CategoryDialog open={categoryDialogOpen} onClose={() => setCategoryDialogOpen(false)} onSave={(name) => { const next = { id: crypto.randomUUID(), name }; onAddCategory(next); setCategoryDialogOpen(false); setCategoryId(next.id); navigate('category', quizPaths.category(next.id), { categoryId: next.id }) }} /></Page>

  if (view === 'category') return <Page><button onClick={() => navigate('categories', quizPaths.categories)} className={secondary}><ArrowLeft size={16} />Categories</button><div className="mt-4 flex items-end justify-between gap-3"><div><span className="text-xs font-medium uppercase tracking-[0.14em] text-purple-600">Category</span><h1 className="mt-1 text-xl font-semibold">{category?.name}</h1></div><div className="flex gap-2"><button type="button" onClick={() => onDeleteCategory(categoryId)} className="flex h-10 items-center justify-center gap-2 rounded-lg bg-red-50 px-3 text-sm font-medium text-red-700 transition-colors hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-500/20 dark:bg-red-500/10 dark:text-red-300 dark:hover:bg-red-500/20"><Trash size={17} />Delete</button><button onClick={() => navigate('create', quizPaths.create(categoryId), { categoryId })} className={primary}><Plus size={17} />Create quiz</button></div></div><div className="mt-4"><section className={surface}><h2 className="text-base font-semibold">Saved quizzes</h2><div className="mt-2 divide-y divide-slate-100 dark:divide-slate-800">{categoryQuizzes.map((item) => <button key={item.id} onClick={() => openQuiz(item)} className="flex min-h-11 w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-colors duration-300 hover:bg-purple-50 dark:hover:bg-purple-500/10"><Exam size={17} className="text-purple-600" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{item.title}</span><span className="text-xs text-slate-500">{item.questions.length} questions</span></span><ArrowRight size={15} /></button>)}{!categoryQuizzes.length && <p className="py-3 text-sm text-slate-500">No saved quizzes yet.</p>}</div></section></div></Page>

  if (view === 'create') return <Page narrow><button onClick={() => navigate('category', quizPaths.category(categoryId), { categoryId })} className={secondary}><ArrowLeft size={16} />{category?.name}</button><form onSubmit={createQuiz} className={`${surface} mt-4`}><h1 className="text-xl font-semibold">Create quiz</h1><p className="mt-0.5 text-sm text-slate-500">Saved under {category?.name}.</p><div className="mt-4 space-y-3"><fieldset><legend className="text-[13px] font-medium">Category</legend><div className="mt-1 flex flex-wrap gap-2">{categories.map((item) => <label key={item.id} className={`cursor-pointer rounded-lg px-3 py-2 text-sm font-medium transition-colors duration-300 ${categoryId === item.id ? 'bg-purple-100 text-purple-800 dark:bg-purple-500/20 dark:text-purple-100' : 'bg-slate-100 text-slate-600 hover:bg-purple-50 dark:bg-slate-800 dark:text-slate-300'}`}><input type="radio" name="quiz-category" value={item.id} checked={categoryId === item.id} onChange={() => { setCategoryId(item.id); navigate('create', quizPaths.create(item.id), { categoryId: item.id }, true) }} className="sr-only" />{item.name}</label>)}</div></fieldset><label className="block"><span className="text-[13px] font-medium">Quiz description</span><textarea required value={description} onChange={(e) => setDescription(e.target.value)} rows="5" className={`${inputClass} mt-1 py-2`} /></label><label className="block"><span className="text-[13px] font-medium">Instructions and format</span><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} rows="4" className={`${inputClass} mt-1 py-2`} /></label></div><Error text={error} /><div className="mt-4 flex justify-end"><button disabled={busy || !description.trim()} className={primary}>{busy ? <SpinnerGap className="animate-spin" /> : <Exam size={17} />}Generate quiz</button></div></form></Page>

  if (view === 'detail') return <Page narrow><button onClick={() => navigate('category', quizPaths.category(quiz.categoryId), { categoryId: quiz.categoryId })} className={secondary}><ArrowLeft size={16} />{category?.name}</button><section className={`${surface} mt-4`}><span className="text-xs font-medium uppercase tracking-[0.14em] text-purple-600">Saved quiz</span><div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-xl font-semibold">{quiz.title}</h1><p className="mt-1 text-sm text-slate-500">{quiz.description}</p><p className="mt-2 text-xs text-slate-500">{quiz.questions.length} questions</p></div><button onClick={takeQuiz} className={`${primary} shrink-0`}><Exam size={17} />Take Quiz</button></div></section><AttemptHistory attempts={attempts} quiz={quiz} onOpen={showAttempt} /></Page>

  if (view === 'result') return <Page narrow><button onClick={() => navigate('detail', quizPaths.detail(quiz.id), { quizId: quiz.id })} className={secondary}><ArrowLeft size={16} />Back to quiz</button><section className={`${surface} mt-4 text-center`}><CheckCircle size={32} weight="fill" className="mx-auto text-purple-600" /><p className="mt-2 text-xs uppercase tracking-[0.14em] text-slate-500">Final result</p><div className="mt-1 flex items-end justify-center gap-3"><span className="text-2xl font-bold">{result.score}<span className="text-sm text-slate-400">/100</span></span><span className="rounded-full bg-purple-100 px-2.5 py-0.5 text-base font-semibold text-purple-800 dark:bg-purple-500/15 dark:text-purple-200">{result.grade}</span></div><p className="mx-auto mt-2 max-w-xl text-sm text-slate-600 dark:text-slate-300">{result.summary}</p><p className="mt-2 text-xs text-slate-500">{attempt ? `Completed ${new Date(attempt.completedAt).toLocaleString()}` : 'This result is final.'}</p></section><section className={`${surface} mt-4`}><h2 className="text-base font-semibold">Question feedback</h2><div className="mt-2 divide-y divide-slate-100 dark:divide-slate-800">{quiz.questions.map((question, index) => { const feedback = result.feedback.find((item) => item.questionId === question.id); const correct = feedback?.correct === true; return <div key={question.id} className="flex gap-3 py-2"><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${correct ? 'bg-green-100 text-green-700 dark:bg-green-500/15 dark:text-green-300' : 'bg-red-100 text-red-700 dark:bg-red-500/15 dark:text-red-300'}`}>{correct ? <CheckCircle size={16} weight="fill" /> : <XCircle size={16} weight="fill" />}</span><div><p className="text-[13px] font-medium">{index + 1}. {question.prompt}</p><p className="mt-0.5 text-sm text-slate-500">Your answer: {Array.isArray(answers[question.id]) ? answers[question.id].join(', ') : String(answers[question.id] ?? '')}</p><p className="mt-0.5 text-sm text-slate-600 dark:text-slate-300">{feedback?.note || 'No detailed feedback provided.'}</p></div></div> })}</div></section><section className={`${surface} mt-4`}><h2 className="text-base font-semibold">Review and next steps</h2><p className="mt-1 text-sm leading-5 text-slate-600 dark:text-slate-300">{result.review || result.summary}</p><p className="mt-2 text-sm leading-5 text-slate-500">{result.advice || 'Review the incorrect answers, revisit their core concepts, then retake the quiz when you are ready.'}</p></section><div className="mx-auto mt-4 grid max-w-md grid-cols-2 gap-2"><button onClick={() => { setAnswers({}); setResult(null); setAttempt(null); navigate('taking', quizPaths.taking(quiz.id), { quizId: quiz.id }) }} className={`${secondary} w-full`}>Retake quiz</button><button onClick={startAnother} className={`${primary} w-full`}>Create another quiz</button></div></Page>

  return <Page narrow><div className="flex items-end justify-between gap-3"><div><span className="text-xs uppercase tracking-[0.14em] text-purple-600">In progress</span><h1 className="mt-1 text-xl font-semibold">{quiz.title}</h1><p className="mt-0.5 text-sm text-slate-500">{quiz.description}</p></div><span className="rounded-full bg-purple-100 px-2.5 py-0.5 text-xs text-purple-700">{count}/{quiz.questions.length}</span></div><div className="mt-4 space-y-3">{quiz.questions.map((question, index) => <section key={question.id} className={surface}><div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-purple-100 font-semibold text-purple-700">{index + 1}</span><div className="min-w-0 flex-1"><h2 className="text-sm font-medium">{question.prompt}</h2><div className="mt-3"><AnswerField question={question} value={answers[question.id]} onChange={(value) => setAnswers((old) => ({ ...old, [question.id]: value }))} disabled={busy} /></div></div></div></section>)}</div><Error text={error} /><div className="mt-4 flex justify-end"><button onClick={submit} disabled={busy} className={primary}>{busy ? <SpinnerGap className="animate-spin" /> : <CheckCircle size={17} />}Submit final answers</button></div></Page>
}

function AttemptHistory({ attempts, quiz, onOpen }) { const quizAttempts = attempts.filter((item) => item.quizId === quiz.id).sort((a, b) => b.completedAt - a.completedAt); return <section className={`${surface} mt-4`}><h2 className="text-base font-semibold">Attempt history</h2><p className="mt-0.5 text-xs text-slate-500">Previous results for this quiz.</p><div className="mt-2 divide-y divide-slate-100 dark:divide-slate-800">{quizAttempts.map((item) => <button key={item.id} onClick={() => onOpen(item)} className="flex min-h-11 w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-colors duration-300 hover:bg-purple-50 dark:hover:bg-purple-500/10"><CheckCircle size={17} className="text-purple-600" /><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{new Date(item.completedAt).toLocaleString()}</span><span className="text-xs text-slate-500">{item.result.score}/100 · {item.result.grade}</span></span><ArrowRight size={15} /></button>)}{!quizAttempts.length && <p className="py-3 text-sm text-slate-500">No attempts for this quiz yet.</p>}</div></section> }

function Error({ text }) { return text ? <p role="alert" className="mt-3 rounded-lg bg-purple-100 px-3 py-2 text-sm text-purple-800 dark:bg-purple-500/15 dark:text-purple-200">{text}</p> : null }
function Page({ children, narrow = false }) { return <div className="relative min-h-0 flex-1 overflow-y-auto px-3 py-3 sm:px-4 sm:py-4 lg:px-6 lg:py-5"><div className={`mx-auto w-full ${narrow ? 'max-w-3xl' : 'max-w-5xl'}`}>{children}</div></div> }
