import { useEffect, useRef, useState } from 'react'
import { CheckCircle, FloppyDisk, Moon, PlugsConnected, SpinnerGap, Sun, Trash, X } from '@phosphor-icons/react'
import Listbox from './Listbox'

const field = 'h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-800 transition-colors duration-300 ease-out placeholder:text-slate-400 hover:border-purple-300 focus:border-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/10 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:hover:border-purple-700'
const focusable = 'button:not([disabled]), input:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'

export default function SettingsPanel({ open, provider, providers, activeProvider, models, status, theme, onThemeChange, onProviderChange, onChange, onAdd, onClose, onLoadModels, onSave, onDelete }) {
  const [showKey, setShowKey] = useState(false)
  const dialogRef = useRef(null)
  const previousFocusRef = useRef(null)
  const onCloseRef = useRef(onClose)
  useEffect(() => { onCloseRef.current = onClose }, [onClose])
  useEffect(() => {
    if (!open) return
    previousFocusRef.current = document.activeElement
    requestAnimationFrame(() => dialogRef.current?.querySelector(focusable)?.focus())
    const keydown = (event) => {
      if (event.key === 'Escape') { event.preventDefault(); onCloseRef.current(); return }
      if (event.key !== 'Tab') return
      const controls = [...(dialogRef.current?.querySelectorAll(focusable) || [])]
      if (!controls.length) return
      const first = controls[0]; const last = controls.at(-1)
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
    }
    document.addEventListener('keydown', keydown)
    return () => { document.removeEventListener('keydown', keydown); previousFocusRef.current?.focus?.() }
  }, [open])
  if (!open) return null
  return <div className="fixed inset-0 z-40 flex h-dvh min-h-0 items-center justify-center overflow-hidden bg-slate-950/50 p-3 backdrop-blur-sm" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}>
    <section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="provider-title" className="flex h-full min-h-0 w-full max-w-xl animate-[pulse_300ms_ease-out_1] flex-col overflow-hidden rounded-xl border border-white/20 bg-white/95 shadow-[0_20px_55px_rgba(15,23,42,0.24)] backdrop-blur-xl motion-reduce:animate-none dark:border-white/10 dark:bg-slate-950/95">
      <header className="z-10 flex h-14 shrink-0 items-center justify-between border-b border-purple-100 bg-white/75 px-4 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/75"><div><h2 id="provider-title" className="text-base leading-6 font-medium text-slate-900 dark:text-white">Provider configuration</h2><p className="text-sm text-slate-500">OpenAI-compatible API</p></div><button onClick={onClose} aria-label="Close settings" className="flex h-9 w-9 cursor-pointer items-center justify-center rounded-lg text-slate-500 transition-[transform,background-color] duration-300 ease-out hover:bg-purple-50 active:scale-[0.97] dark:hover:bg-purple-500/10"><X size={18} /></button></header>
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto overscroll-contain p-4 [scrollbar-gutter:stable]">
        <Listbox label="Active provider" value={activeProvider} options={providers} onChange={onProviderChange} />
        <div><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">Theme</span><div role="radiogroup" aria-label="Display theme" className="grid grid-cols-2 gap-2"><button role="radio" aria-checked={theme === 'light'} onClick={() => onThemeChange('light')} className={`flex h-10 cursor-pointer items-center justify-center gap-2 rounded-lg transition-colors duration-300 ${theme === 'light' ? 'bg-purple-100 font-medium text-purple-800 dark:bg-purple-500/20 dark:text-purple-200' : 'bg-slate-100 text-slate-600 hover:bg-purple-50 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-purple-500/10'}`}><Sun size={17} />Light</button><button role="radio" aria-checked={theme === 'dark'} onClick={() => onThemeChange('dark')} className={`flex h-10 cursor-pointer items-center justify-center gap-2 rounded-lg transition-colors duration-300 ${theme === 'dark' ? 'bg-purple-100 font-medium text-purple-800 dark:bg-purple-500/20 dark:text-purple-200' : 'bg-slate-100 text-slate-600 hover:bg-purple-50 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-purple-500/10'}`}><Moon size={17} />Dark</button></div></div>
        <div className="relative overflow-hidden rounded-xl bg-gradient-to-br from-purple-100 to-white p-4 shadow-[0_8px_24px_rgba(76,29,149,0.10)] transition-transform duration-500 motion-reduce:transform-none dark:from-purple-500/15 dark:to-slate-900"><p className="text-sm font-medium text-purple-900 dark:text-purple-200">Endpoints in use</p><p className="mt-1 break-all text-sm text-purple-700 dark:text-purple-300">GET /models · POST /chat/completions</p></div>
        <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">Provider name</span><input className={field} value={provider.name} onChange={(e) => onChange('name', e.target.value)} placeholder="Example: OpenRouter" /></label>
        <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">Base URL</span><input className={field} value={provider.baseUrl} onChange={(e) => onChange('baseUrl', e.target.value)} placeholder="https://api.example.com/v1" inputMode="url" /></label>
        <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">API key</span><div className="flex gap-2"><input className={field} value={provider.apiKey} onChange={(e) => onChange('apiKey', e.target.value)} placeholder="sk-..." type={showKey ? 'text' : 'password'} autoComplete="off" /><button type="button" onClick={() => setShowKey(!showKey)} className="h-10 shrink-0 cursor-pointer rounded-lg bg-slate-100 px-3 text-sm font-medium text-slate-700 transition-colors duration-300 ease-out hover:bg-purple-100 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-purple-500/15">{showKey ? 'Hide' : 'Show'}</button></div><span className="mt-1 block text-sm text-slate-500">Stored only in this device's browser.</span></label>
        <button onClick={onLoadModels} disabled={status.loading || !provider.baseUrl} className="flex h-10 w-full cursor-pointer items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-purple-700 to-purple-500 px-4 text-sm font-medium text-white shadow-[0_8px_22px_rgba(126,34,206,0.20)] transition-[transform,box-shadow] duration-300 ease-out  focus:outline-none focus:ring-2 focus:ring-purple-500/10 active:scale-[0.97] disabled:cursor-not-allowed disabled:opacity-50 motion-reduce:transform-none">{status.loading ? <SpinnerGap size={17} className="animate-spin motion-reduce:animate-none" /> : <PlugsConnected size={17} />}Test connection & fetch models</button>
        {status.message && <p role="status" className={`flex items-start gap-2 rounded-lg p-3 text-sm ${status.ok ? 'bg-purple-50 text-purple-800 dark:bg-purple-500/10 dark:text-purple-200' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200'}`}>{status.ok && <CheckCircle size={17} className="mt-0.5 shrink-0" weight="fill" />}{status.message}</p>}
        {models.length > 0 && <p className="rounded-lg bg-slate-100 p-3 text-sm text-slate-600 dark:bg-slate-800 dark:text-slate-300">{models.length} models available. Select one from the chat input area.</p>}
        <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">Additional instructions</span><textarea rows="4" className="w-full resize-y rounded-md border border-slate-200 bg-white p-3 text-sm text-slate-800 transition-colors duration-300 ease-out placeholder:text-slate-400 focus:border-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/10 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" value={provider.instructions ?? ''} onChange={(e) => onChange('instructions', e.target.value)} placeholder="Example: Keep answers concise and include brief examples." /><span className="mt-1 block text-sm text-slate-500">These instructions are sent as a system prompt in every conversation.</span></label>
        <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700 dark:text-slate-300">Model context capacity</span><div className="relative"><input className={`${field} pr-16 tabular-nums`} value={provider.contextWindow ?? 128000} onChange={(e) => onChange('contextWindow', Math.max(1, Number(e.target.value)))} type="number" min="1" step="1000" inputMode="numeric" /><span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-sm text-slate-400">token</span></div><span className="mt-1 block text-sm text-slate-500">Use the model documentation value for an accurate context percentage.</span></label>
        <details className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><summary className="cursor-pointer text-sm font-medium text-slate-700 dark:text-slate-300">Additional headers (JSON)</summary><textarea rows="4" className="mt-3 w-full resize-y rounded-md border border-slate-200 bg-white p-3 text-sm text-slate-800 transition-colors duration-300 ease-out focus:border-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/10 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100" value={provider.headersText} onChange={(e) => onChange('headersText', e.target.value)} placeholder={'{"HTTP-Referer":"https://app.example"}'} /></details>
        <div className="flex gap-2 pt-2"><button onClick={onAdd} className="flex h-10 cursor-pointer items-center justify-center rounded-lg bg-slate-100 px-3 text-sm font-medium text-slate-700 transition-colors duration-300 ease-out hover:bg-purple-100 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-purple-500/15">New</button><button onClick={onDelete} className="flex h-10 cursor-pointer items-center justify-center gap-2 rounded-lg bg-slate-100 px-3 text-sm font-medium text-slate-700 transition-colors duration-300 ease-out hover:bg-purple-100 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-purple-500/15"><Trash size={17} />Reset</button><button onClick={onSave} className="flex h-10 flex-1 cursor-pointer items-center justify-center gap-2 rounded-lg bg-purple-600 px-4 text-sm font-medium text-white transition-[transform,background-color] duration-300 ease-out hover:bg-purple-700 active:scale-[0.97] motion-reduce:transform-none"><FloppyDisk size={17} />Save provider</button></div>
      </div>
    </section>
  </div>
}
